name: wuwa
description: wuwa tools
version: 0.5.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13 
  json_serializable: ^6.9.0
  lints: ^4.0.0
  test: ^1.24.0
